language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
script:
  - py.test --cov=openedx_webhooks
  - cd docs && make html
after_success:
  - codecov
