sudo: false
language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements/test.txt
script:
  - python manage.py dbcreate
  - make test
  - cd docs && make html
  - cd ..
after_success:
  - codecov
branches:
    only:
      - master
      - development
